apiVersion: v1
kind: Service
metadata:
  name: em-api-svc
  labels:
    app.kubernetes.io/part-of: employeemanagement
spec:
  type: LoadBalancer
  selector:
    app: em-api
  ports:
  - port: 8081
    targetPort: 80