apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-svc
  labels:
    app.kubernetes.io/part-of: employeemanagement
spec:
  type: ClusterIP
  selector:
    app: postgresql-db
  ports:
  - port: 5432
    targetPort: 5432