apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  selector:
    matchLabels:
      app: sqlserver-pod
  template:
    metadata:
      labels:
        app: sqlserver-pod
    spec:
      containers:
      - name: sqlserver-container
        image: mcr.microsoft.com/mssql/server
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "1Secure*Password1"
          - name: MSSQL_PID
            value: "Developer"
        volumeMounts:
          - name: sqldb
            mountPath: /var/opt/mssql/data
      volumes:
        - name: sqldb
          persistentVolumeClaim:
            claimName: sqlserver-pvc
