name: Test API CI

on:
  pull_request:
    bransches: [main]
  push:
    bransches: [UnitTests]
  
jobs:
  api-test:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
        dotnet-version: 5.0.102
       
      - name: Install Dependencies 
        run: dotnet restore
        working-directory: EmployeeManagement.WebApi.Test/
       
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: EmployeeManagement.WebApi.Test/
       
      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal
        working-directory: EmployeeManagement.WebApi.Test/
       
